### ISSUE TITLE
Upgrade fails for alembic > v0.7.x

### ISSUE THREAD

**Issue by sunny2get** [ibmdb/python-ibmdbalembic#6]
The failure happens when you try to run upgrade. Alembic now expects a result to be returned when updating the version in `alembic_version` table (https://bitbucket.org/zzzeek/alembic/src/1a6d6cddbb82b7ffb4a9cb73a4836fb5268699e5/alembic/runtime/migration.py?at=master&fileviewer=file-view-default#migration.py-483:489)

The code in question is: 

```
if not self.context.as_sql and ret.rowcount != 1:
            raise util.CommandError(
                "Online migration expected to match one "
                "row when updating '%s' to '%s' in '%s'; "
                "%d found"
                % (from_, to_, self.context.version_table, ret.rowcount))
```

However, the current exec function (https://github.com/ibmdb/python-ibmdbalembic/blob/master/ibm_db_alembic/ibm_db_alembic/ibm_db.py#L52-L68) wont return anything, therefore it fails. 

Similar issues were reported with Oracle and MSSQL here: https://bitbucket.org/zzzeek/alembic/issues/253

I will create a PR if everyone is ok with similar change as was used for fixing Oracle here: https://bitbucket.org/zzzeek/alembic/commits/206143c9b1f5

**Comment by sunny2get** [comment]
UPDATE: So, when I forked the repo and saw the code for `ibm_db.py` file I see the changes are all there that I was expecting to make. 

However, my own local version when installed with `pip` doesn't have any of these changes. The package is pulled from: http://pypi.python.org/pypi/ibm_db_alembic/

Unzip the tar and you would see the `_exec` function doesn't return a result and therefore the error when upgrading.

I guess this issue now becomes: 

> Updating the pip package with latest code from this repo.

I will willing to volunteer if someone can point me to the instructions for doing so.

Thanks

**Comment by abhi7436** [comment]
Hi,
As of now there is no development plan for the ibmdbalembic, Since we work on open source projects based on demand, Since in last 3 year there were no request for ibmdbalembic, we don't have any development plan. 
We see most demands are for Django and SQLAlchemy, hence working on same.

Regards,
Abhinav

**Comment by sunny2get** [comment]
Hi Abhinav,

Thanks for your reply. I understand that this is not a priority but the package published on pip is misleading and I spent good amount of a day to figure out what might be the issue. All I ask is to publish a latest tar of this current state of the code to pip index so that others who want to use it dont run into the same issues.

Thanks

**Comment by abhi7436** [comment]
Hi Sunny ,
@sunny2get  We have published new version with this code changes in PIP.
Thanks for pointing out the issue.

Thanks,
Abhinav

**Comment by sunny2get** [comment]
Thanks Abhinav..glad we figured this out.
